### ISSUE TITLE
Could you tell me which version you using?

### ISSUE THREAD

**Issue by Juddd** [sturkmen72/opencv_samples#1]
I'm in vs2015 and opencv 3.2,I cannot use your [this code](https://github.com/sturkmen72/opencv_samples/blob/master/171913.cpp)

**Comment by sturkmen72** [comment]
what is the error message?

**Comment by Juddd** [comment]
The error message is like [this](http://i.stack.imgur.com/MmOAh.png),which version do you using.And I note you just use one image?My intension is hope if the empty paper is [this](https://i.stack.imgur.com/euyxY.jpg).The target is [this](https://i.stack.imgur.com/fymre.jpg).Then [this](https://i.stack.imgur.com/LA2mC.jpg) is expected result.I mean the nature is image registration about two image with some same information but maybe difference size

**Comment by sturkmen72** [comment]
problem seems unrelated with the code..
can you run [this](https://github.com/sturkmen72/opencv_samples/blob/master/mouse_test.cpp)

**Comment by Juddd** [comment]
That is [work](http://i.stack.imgur.com/eNSLN.png) well..

**Comment by sturkmen72** [comment]
i changed [the code](https://github.com/sturkmen72/opencv_samples/blob/master/171913.cpp#L135-L144) to try to find problem
could you try it.
lets check it step by step

**Comment by Juddd** [comment]
I get a same error windows..

**Comment by sturkmen72** [comment]
let me see screenshot

**Comment by Juddd** [comment]
Totally [same error](http://i.stack.imgur.com/IJ74H.png)

**Comment by sturkmen72** [comment]
https://github.com/sturkmen72/opencv_samples/commit/0d644ee85d29560b39137bd4d3c0782405b05e65
by the change above the code works with test image created by itself
can you send the image you tried?

**Comment by Juddd** [comment]
This is [my code](http://i.stack.imgur.com/Yq7va.png) and this is [my image](https://i.stack.imgur.com/uwcXx.jpg) I have tried

**Comment by sturkmen72** [comment]
it works without problem with your image in release mode ( do you use it in debug )

**Comment by sturkmen72** [comment]
imread does not support non english chars i think the problem is http://i.stack.imgur.com/Yq7va.png

**Comment by Juddd** [comment]
That is ....exciting...It is support non-English. After a change the mode to release,the problem is disapear,but a little problem is I cannot show all the image in my screen ,I mean this image is two large,could you help to import it to my local disk?
